const ActionType = {
    SEARCH_INPUT_CHANGE: "SEARCH_INPUT_CHANGE",
    GET_SELECTED_ADDRESS: "GET_SELECTED_ADDRESS",
    GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
    SHOW_PLACE_INFO: "SHOW_PLACE_INFO"
}

export default ActionType;